# Generated by Django 6.1.1 on 2026-09-23 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('superficie', models.FloatField()),
                ('consomation_electrique', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('prix', models.FloatField()),
                ('duree_de_vie', models.FloatField()),
                ('cout_de_maintenance', models.FloatField()),
                ('superficie', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('tva', models.FloatField()),
                ('tarif_electrique', models.FloatField()),
                ('salaire_minimum', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('cout', models.FloatField()),
                ('heure_de_travail', models.FloatField()),
                ('consomation_electrique', models.FloatField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.machine')),
                ('operation_suivante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.operation')),
            ],
        ),
        migrations.CreateModel(
            name='Point_de_vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('heure_de_travail', models.FloatField()),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('prix_de_vente', models.FloatField()),
                ('duree_de_vie', models.FloatField()),
                ('nombre_par_palette', models.IntegerField()),
                ('operations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.operation')),
            ],
        ),
        migrations.CreateModel(
            name='Prix_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_achat', models.FloatField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_achat', models.FloatField()),
                ('produit', models.ManyToManyField(to='high_level.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Quantite_machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
                ('type_machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.machine')),
            ],
        ),
        migrations.CreateModel(
            name='QuantiteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.produit')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='quantite_produit',
            field=models.ManyToManyField(to='high_level.quantiteproduit'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='quantite_machines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.quantiteproduit'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction', models.FloatField()),
                ('client', models.CharField()),
                ('Point_de_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.point_de_vente')),
                ('quantite_produit', models.ManyToManyField(to='high_level.quantiteproduit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palettes_max', models.IntegerField()),
                ('quantite_produit', models.ManyToManyField(to='high_level.quantiteproduit')),
            ],
        ),
        migrations.AddField(
            model_name='point_de_vente',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.stock'),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_palettes', models.IntegerField()),
                ('cout', models.FloatField()),
                ('delai', models.FloatField()),
                ('arrive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.lieu')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depart+', to='high_level.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('taxe_immobiliere', models.CharField()),
                ('prix_metre_carre', models.FloatField()),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.pays')),
            ],
        ),
        migrations.AddField(
            model_name='lieu',
            name='ville',
            field=models.ManyToManyField(to='high_level.ville'),
        ),
    ]
