# Generated by Django 6.1.1 on 2026-09-29 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_level', '0002_alter_produit_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='quantite_machines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.quantite_machine'),
        ),
    ]
