# Generated by Django 6.1.1 on 2026-09-29 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_level', '0003_alter_lieu_quantite_machines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quantite_machine',
            name='type_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='high_level.machine'),
        ),
    ]
