# Generated by Django 6.1.1 on 2026-09-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_level', '0004_alter_operation_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='quantite_produit',
            field=models.ManyToManyField(blank=True, null=True, to='high_level.quantiteproduit'),
        ),
    ]
